#NOMBRE DE LA APLICACION
spring.application.name=CiberElectrik
#DEFINIR EL PUERTO DE LA APLICACION
server.port=8999
#URL DEL PROYECTO
server.servlet.context-path=/ciberelectrik
#CADENA DE CONEXION
#spring.datasource.url=jdbc:mysql://localhost:3306/bdciberelectrik20261?useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.url=jdbc:mysql://localhost:3306/bdciberelectrik20261v2
#USUARIO DE LA BD
spring.datasource.username=root
#CLAVE DE LA BD
spring.datasource.password=root
#DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#CONFIGURANDO EL THYMELEAF
#define la carpeta donde Spring buscara las vistas
spring.thymeleaf.prefix=classpath:/templates/
#indica la extension de los archivos de la vista
spring.thymeleaf.suffix=.html
#define el modo de procesamiento de plantillas
spring.thymeleaf.mode=HTML
#configurar la codificacion de caracteres
spring.thymeleaf.encoding=UTF-8
#desactiva la cache de las plantillas
spring.thymeleaf.cache=false